### ISSUE TITLE
Error: Timeout: did not get to load all resources on this page

### ISSUE THREAD

**Issue by mhulse** [mhulse/kludgy#31]
Just got this the other day:

```bash
$ kludgy "xxxxxxxxxxxxxxxxxxxxxxxx"
/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:594
            throw error;
            ^

Error: Timeout: did not get to load all resources on this page
    at Timeout.timeout (/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:601:38)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
Error: Must specify panoID with --id option
    at Promise (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:42:34)
    at parseLocation (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:34:1)
    at Module._compile (module.js:413:34)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/kludgy/node_modules/devtool/lib/require-hook.js:32:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/kludgy/node_modules/devtool/lib/preload.js:78:16)
Error: Format error in file - /usr/local/lib/node_modules/kludgy/panos/.jpg
```

I have yet to reproduce.

Related: #30, because it might be nice to see where it gets stuck. So, like a verbose mode.

Also, setting a timeout that is like 30 seconds could be nice. IIRC, this took a while to return.

**Comment by mhulse** [comment]
Seeing this at home too:

```bash
$ kludgy "xxxxxxxxxxxx"

/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:594
            throw error;
            ^

Error: Timeout: did not get to load all resources on this page
    at Timeout.timeout (/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:601:38)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
Error: Must specify panoID with --id option
    at Promise (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:42:34)
    at parseLocation (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:34:1)
    at Module._compile (module.js:413:34)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/kludgy/node_modules/devtool/lib/require-hook.js:32:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/kludgy/node_modules/devtool/lib/preload.js:78:16)
Error: Format error in file - /usr/local/lib/node_modules/kludgy/panos/.jpg
```

**Comment by mhulse** [comment]
Maybe:

https://github.com/assaf/zombie/issues/986#issuecomment-163625064

**Comment by mhulse** [comment]
This is no longer an issue in v2.

Closing.
