### ISSUE TITLE
Problem with command for GPS

### ISSUE THREAD

**Issue by mhulse** [mhulse/kludgy#54]
```bash
Failed to write GPS coordinates
Program error, exiting!
TypeError: commands[o.command] is not a function
    at execute (/Users/mhulse/dev/github/mhulse/kludgy/node_modules/simple-gps/index.js:38:26)
    at validate (/Users/mhulse/dev/github/mhulse/kludgy/node_modules/simple-gps/index.js:107:18)
after
```

**Comment by mhulse** [comment]
Solved. I forget the fix, but it's fixed.
